# Generated by Django 4.2.15 on 2024-08-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vege', '0005_alter_student_options'),
        ('accounts', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
