from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as db 

class Ui_bill(object):

    def Insert(self):
        id = self.id_in.text()
        name = self.name_in.text()
        price = int(self.price_in.text())
        qty = int(self.qty_in.text())
        total = str(price * qty)

        if(name=="" or price=="" or qty=="" ):
            QtWidgets.QMessageBox.information(None, "Alert", "Please Enter all Fields!")
        else:
            mydb = db.connect(host="localhost", user="root", password="", database="bitdb")
            cursor = mydb.cursor()
            query = "INSERT INTO bill values('"+id+"','"+name+"','"+str(price)+"', '"+str(qty)+"', '"+str(total)+"')"
            cursor.execute(query)
            cursor.execute("commit")

    def FetchData(self):
        try:
            mydb = db.connect(host="localhost", user="root", password="", database="bitdb")
            cursor = mydb.cursor()
            query = "SELECT * FROM bill"
            cursor.execute(query)
            results = cursor.fetchall()
        
            for row in results:
                print(f"ID: {row[0]}, Name: {row[1]}, Price: {row[2]}, Quantity: {row[3]}, Total: {row[4]}")
        
                QtWidgets.QMessageBox.information(None, "Success", "Data fetched successfully!")
        except db.Error as e:
            QtWidgets.QMessageBox.information(None, "Error", f"Database error: {e}")
        finally:
            cursor.close()
        mydb.close()



    def setupUi(self, bill):
        bill.setObjectName("bill")
        bill.resize(798, 488)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(200, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        bill.setPalette(palette)
        bill.setAutoFillBackground(True)
        self.label = QtWidgets.QLabel(bill)
        self.label.setGeometry(QtCore.QRect(310, 20, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.name = QtWidgets.QLabel(bill)
        self.name.setGeometry(QtCore.QRect(120, 170, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.price = QtWidgets.QLabel(bill)
        self.price.setGeometry(QtCore.QRect(120, 220, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.price.setFont(font)
        self.price.setObjectName("price")
        self.qty = QtWidgets.QLabel(bill)
        self.qty.setGeometry(QtCore.QRect(120, 270, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.qty.setFont(font)
        self.qty.setObjectName("qty")
        self.tot = QtWidgets.QLabel(bill)
        self.tot.setGeometry(QtCore.QRect(120, 320, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tot.setFont(font)
        self.tot.setObjectName("tot")
        self.name_in = QtWidgets.QLineEdit(bill)
        self.name_in.setGeometry(QtCore.QRect(270, 170, 113, 22))
        self.name_in.setObjectName("name_in")
        self.price_in = QtWidgets.QLineEdit(bill)
        self.price_in.setGeometry(QtCore.QRect(270, 220, 113, 22))
        self.price_in.setObjectName("price_in")
        self.total = QtWidgets.QLineEdit(bill)
        self.total.setGeometry(QtCore.QRect(270, 320, 113, 22))
        self.total.setObjectName("total")
        self.insert = QtWidgets.QPushButton(bill)
        self.insert.setGeometry(QtCore.QRect(590, 120, 93, 28))
        self.insert.setObjectName("insert")
        self.update = QtWidgets.QPushButton(bill)
        self.update.setGeometry(QtCore.QRect(590, 170, 93, 28))
        self.update.setObjectName("update")
        self.delete_2 = QtWidgets.QPushButton(bill)
        self.delete_2.setGeometry(QtCore.QRect(590, 220, 93, 28))
        self.delete_2.setObjectName("delete_2")
        self.select = QtWidgets.QPushButton(bill)
        self.select.setGeometry(QtCore.QRect(590, 270, 93, 28))
        self.select.setObjectName("select")
        self.all = QtWidgets.QLineEdit(bill)
        self.all.setGeometry(QtCore.QRect(200, 410, 401, 31))
        self.all.setObjectName("all")
        self.id = QtWidgets.QLabel(bill)
        self.id.setGeometry(QtCore.QRect(120, 120, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.id.setFont(font)
        self.id.setObjectName("id")
        self.id_in = QtWidgets.QLineEdit(bill)
        self.id_in.setGeometry(QtCore.QRect(270, 120, 113, 22))
        self.id_in.setObjectName("id_in")
        self.qty_in = QtWidgets.QSpinBox(bill)
        self.qty_in.setGeometry(QtCore.QRect(270, 270, 111, 22))
        self.qty_in.setObjectName("qty_in")

        self.retranslateUi(bill)
        QtCore.QMetaObject.connectSlotsByName(bill)
        self.insert.clicked.connect(self.Insert)
        self.select.clicked.connect(self.FetchData)

    def retranslateUi(self, bill):
        _translate = QtCore.QCoreApplication.translate
        bill.setWindowTitle(_translate("bill", "Billing System"))
        self.label.setText(_translate("bill", "Billing System"))
        self.name.setText(_translate("bill", "Product Name"))
        self.price.setText(_translate("bill", "Price"))
        self.qty.setText(_translate("bill", "Quantity"))
        self.tot.setText(_translate("bill", "Total"))
        self.insert.setText(_translate("bill", "Insert"))
        self.update.setText(_translate("bill", "Update"))
        self.delete_2.setText(_translate("bill", "Delete"))
        self.select.setText(_translate("bill", "Select"))
        self.id.setText(_translate("bill", "id"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    bill = QtWidgets.QWidget()
    ui = Ui_bill()
    ui.setupUi(bill)
    bill.show()
    sys.exit(app.exec_())
