# Generated by Django 4.2.15 on 2024-08-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_fan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
